//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пользователь.
    /// </summary>
    // *** Start programmer edit section *** (Пользователь CustomAttributes)

    // *** End programmer edit section *** (Пользователь CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПользовательE", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'",
            "НомерТелефона as \'Номер телефона\'",
            "Транзакция as \'Транзакция\'",
            "Транзакция.Дата as \'Дата\'",
            "Транзакция.Время as \'Время\'",
            "Транзакция.Оплата as \'Оплата\'",
            "Транзакция.Сумма as \'Сумма\'"})]
    [View("ПользовательL", new string[] {
            "ID as \'ID\'",
            "ФИО as \'ФИО\'",
            "НомерТелефона as \'Номер телефона\'",
            "Транзакция.Дата as \'Дата\'",
            "Транзакция.Время as \'Время\'",
            "Транзакция.Оплата as \'Оплата\'",
            "Транзакция.Сумма as \'Сумма\'"})]
    public class Пользователь : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fФИО;
        
        private int fНомерТелефона;
        
        private IIS.Postamat.Транзакция fТранзакция;
        
        // *** Start programmer edit section *** (Пользователь CustomMembers)

        // *** End programmer edit section *** (Пользователь CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Пользователь.ID CustomAttributes)

        // *** End programmer edit section *** (Пользователь.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Пользователь.ID Get start)

                // *** End programmer edit section *** (Пользователь.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Пользователь.ID Get end)

                // *** End programmer edit section *** (Пользователь.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пользователь.ID Set start)

                // *** End programmer edit section *** (Пользователь.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Пользователь.ID Set end)

                // *** End programmer edit section *** (Пользователь.ID Set end)
            }
        }
        
        /// <summary>
        /// НомерТелефона.
        /// </summary>
        // *** Start programmer edit section *** (Пользователь.НомерТелефона CustomAttributes)

        // *** End programmer edit section *** (Пользователь.НомерТелефона CustomAttributes)
        public virtual int НомерТелефона
        {
            get
            {
                // *** Start programmer edit section *** (Пользователь.НомерТелефона Get start)

                // *** End programmer edit section *** (Пользователь.НомерТелефона Get start)
                int result = this.fНомерТелефона;
                // *** Start programmer edit section *** (Пользователь.НомерТелефона Get end)

                // *** End programmer edit section *** (Пользователь.НомерТелефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пользователь.НомерТелефона Set start)

                // *** End programmer edit section *** (Пользователь.НомерТелефона Set start)
                this.fНомерТелефона = value;
                // *** Start programmer edit section *** (Пользователь.НомерТелефона Set end)

                // *** End programmer edit section *** (Пользователь.НомерТелефона Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Пользователь.ФИО CustomAttributes)

        // *** End programmer edit section *** (Пользователь.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Пользователь.ФИО Get start)

                // *** End programmer edit section *** (Пользователь.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Пользователь.ФИО Get end)

                // *** End programmer edit section *** (Пользователь.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пользователь.ФИО Set start)

                // *** End programmer edit section *** (Пользователь.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Пользователь.ФИО Set end)

                // *** End programmer edit section *** (Пользователь.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Пользователь.
        /// </summary>
        // *** Start programmer edit section *** (Пользователь.Транзакция CustomAttributes)

        // *** End programmer edit section *** (Пользователь.Транзакция CustomAttributes)
        [PropertyStorage(new string[] {
                "Транзакция"})]
        [NotNull()]
        public virtual IIS.Postamat.Транзакция Транзакция
        {
            get
            {
                // *** Start programmer edit section *** (Пользователь.Транзакция Get start)

                // *** End programmer edit section *** (Пользователь.Транзакция Get start)
                IIS.Postamat.Транзакция result = this.fТранзакция;
                // *** Start programmer edit section *** (Пользователь.Транзакция Get end)

                // *** End programmer edit section *** (Пользователь.Транзакция Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пользователь.Транзакция Set start)

                // *** End programmer edit section *** (Пользователь.Транзакция Set start)
                this.fТранзакция = value;
                // *** Start programmer edit section *** (Пользователь.Транзакция Set end)

                // *** End programmer edit section *** (Пользователь.Транзакция Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПользовательE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПользовательE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПользовательE", typeof(IIS.Postamat.Пользователь));
                }
            }
            
            /// <summary>
            /// "ПользовательL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПользовательL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПользовательL", typeof(IIS.Postamat.Пользователь));
                }
            }
        }
    }
}
