//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Служба доставки.
    /// </summary>
    // *** Start programmer edit section *** (СлужбаДоставки CustomAttributes)

    // *** End programmer edit section *** (СлужбаДоставки CustomAttributes)
    [AutoAltered()]
    [Caption("Служба доставки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СлужбаДоставкиE", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'",
            "НомерТелефона as \'Номер телефона\'"})]
    [View("СлужбаДоставкиL", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'",
            "НомерТелефона as \'Номер телефона\'"})]
    public class СлужбаДоставки : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fНаименование;
        
        private string fАдрес;
        
        private string fНомерТелефона;
        
        // *** Start programmer edit section *** (СлужбаДоставки CustomMembers)

        // *** End programmer edit section *** (СлужбаДоставки CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (СлужбаДоставки.ID CustomAttributes)

        // *** End programmer edit section *** (СлужбаДоставки.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (СлужбаДоставки.ID Get start)

                // *** End programmer edit section *** (СлужбаДоставки.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (СлужбаДоставки.ID Get end)

                // *** End programmer edit section *** (СлужбаДоставки.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СлужбаДоставки.ID Set start)

                // *** End programmer edit section *** (СлужбаДоставки.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (СлужбаДоставки.ID Set end)

                // *** End programmer edit section *** (СлужбаДоставки.ID Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (СлужбаДоставки.Адрес CustomAttributes)

        // *** End programmer edit section *** (СлужбаДоставки.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Адрес Get start)

                // *** End programmer edit section *** (СлужбаДоставки.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (СлужбаДоставки.Адрес Get end)

                // *** End programmer edit section *** (СлужбаДоставки.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Адрес Set start)

                // *** End programmer edit section *** (СлужбаДоставки.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (СлужбаДоставки.Адрес Set end)

                // *** End programmer edit section *** (СлужбаДоставки.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СлужбаДоставки.Наименование CustomAttributes)

        // *** End programmer edit section *** (СлужбаДоставки.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Наименование Get start)

                // *** End programmer edit section *** (СлужбаДоставки.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СлужбаДоставки.Наименование Get end)

                // *** End programmer edit section *** (СлужбаДоставки.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СлужбаДоставки.Наименование Set start)

                // *** End programmer edit section *** (СлужбаДоставки.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СлужбаДоставки.Наименование Set end)

                // *** End programmer edit section *** (СлужбаДоставки.Наименование Set end)
            }
        }
        
        /// <summary>
        /// НомерТелефона.
        /// </summary>
        // *** Start programmer edit section *** (СлужбаДоставки.НомерТелефона CustomAttributes)

        // *** End programmer edit section *** (СлужбаДоставки.НомерТелефона CustomAttributes)
        [StrLen(255)]
        public virtual string НомерТелефона
        {
            get
            {
                // *** Start programmer edit section *** (СлужбаДоставки.НомерТелефона Get start)

                // *** End programmer edit section *** (СлужбаДоставки.НомерТелефона Get start)
                string result = this.fНомерТелефона;
                // *** Start programmer edit section *** (СлужбаДоставки.НомерТелефона Get end)

                // *** End programmer edit section *** (СлужбаДоставки.НомерТелефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СлужбаДоставки.НомерТелефона Set start)

                // *** End programmer edit section *** (СлужбаДоставки.НомерТелефона Set start)
                this.fНомерТелефона = value;
                // *** Start programmer edit section *** (СлужбаДоставки.НомерТелефона Set end)

                // *** End programmer edit section *** (СлужбаДоставки.НомерТелефона Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СлужбаДоставкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СлужбаДоставкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СлужбаДоставкиE", typeof(IIS.Postamat.СлужбаДоставки));
                }
            }
            
            /// <summary>
            /// "СлужбаДоставкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СлужбаДоставкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СлужбаДоставкиL", typeof(IIS.Postamat.СлужбаДоставки));
                }
            }
        }
    }
}
