//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Транзакция.
    /// </summary>
    // *** Start programmer edit section *** (Транзакция CustomAttributes)

    // *** End programmer edit section *** (Транзакция CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТранзакцияE", new string[] {
            "ID as \'ID\'",
            "Дата as \'Дата\'",
            "Время as \'Время\'",
            "Оплата as \'Оплата\'",
            "Сумма as \'Сумма\'"})]
    [AssociatedDetailViewAttribute("ТранзакцияE", "Посылка", "ПосылкаE", true, "", "Посылка", true, new string[] {
            ""})]
    [View("ТранзакцияL", new string[] {
            "ID",
            "Время",
            "Дата",
            "Оплата",
            "Сумма"})]
    public class Транзакция : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private System.DateTime fДата;
        
        private string fВремя;
        
        private IIS.Postamat.Оплата fОплата;
        
        private double fСумма;
        
        private IIS.Postamat.DetailArrayOfПосылка fПосылка;
        
        // *** Start programmer edit section *** (Транзакция CustomMembers)

        // *** End programmer edit section *** (Транзакция CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Транзакция.ID CustomAttributes)

        // *** End programmer edit section *** (Транзакция.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Транзакция.ID Get start)

                // *** End programmer edit section *** (Транзакция.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Транзакция.ID Get end)

                // *** End programmer edit section *** (Транзакция.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Транзакция.ID Set start)

                // *** End programmer edit section *** (Транзакция.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Транзакция.ID Set end)

                // *** End programmer edit section *** (Транзакция.ID Set end)
            }
        }
        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (Транзакция.Время CustomAttributes)

        // *** End programmer edit section *** (Транзакция.Время CustomAttributes)
        [StrLen(255)]
        public virtual string Время
        {
            get
            {
                // *** Start programmer edit section *** (Транзакция.Время Get start)

                // *** End programmer edit section *** (Транзакция.Время Get start)
                string result = this.fВремя;
                // *** Start programmer edit section *** (Транзакция.Время Get end)

                // *** End programmer edit section *** (Транзакция.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Транзакция.Время Set start)

                // *** End programmer edit section *** (Транзакция.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (Транзакция.Время Set end)

                // *** End programmer edit section *** (Транзакция.Время Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Транзакция.Дата CustomAttributes)

        // *** End programmer edit section *** (Транзакция.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Транзакция.Дата Get start)

                // *** End programmer edit section *** (Транзакция.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Транзакция.Дата Get end)

                // *** End programmer edit section *** (Транзакция.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Транзакция.Дата Set start)

                // *** End programmer edit section *** (Транзакция.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Транзакция.Дата Set end)

                // *** End programmer edit section *** (Транзакция.Дата Set end)
            }
        }
        
        /// <summary>
        /// Оплата.
        /// </summary>
        // *** Start programmer edit section *** (Транзакция.Оплата CustomAttributes)

        // *** End programmer edit section *** (Транзакция.Оплата CustomAttributes)
        public virtual IIS.Postamat.Оплата Оплата
        {
            get
            {
                // *** Start programmer edit section *** (Транзакция.Оплата Get start)

                // *** End programmer edit section *** (Транзакция.Оплата Get start)
                IIS.Postamat.Оплата result = this.fОплата;
                // *** Start programmer edit section *** (Транзакция.Оплата Get end)

                // *** End programmer edit section *** (Транзакция.Оплата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Транзакция.Оплата Set start)

                // *** End programmer edit section *** (Транзакция.Оплата Set start)
                this.fОплата = value;
                // *** Start programmer edit section *** (Транзакция.Оплата Set end)

                // *** End programmer edit section *** (Транзакция.Оплата Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Транзакция.Сумма CustomAttributes)

        // *** End programmer edit section *** (Транзакция.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Транзакция.Сумма Get start)

                // *** End programmer edit section *** (Транзакция.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Транзакция.Сумма Get end)

                // *** End programmer edit section *** (Транзакция.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Транзакция.Сумма Set start)

                // *** End programmer edit section *** (Транзакция.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Транзакция.Сумма Set end)

                // *** End programmer edit section *** (Транзакция.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Транзакция.
        /// </summary>
        // *** Start programmer edit section *** (Транзакция.Посылка CustomAttributes)

        // *** End programmer edit section *** (Транзакция.Посылка CustomAttributes)
        public virtual IIS.Postamat.DetailArrayOfПосылка Посылка
        {
            get
            {
                // *** Start programmer edit section *** (Транзакция.Посылка Get start)

                // *** End programmer edit section *** (Транзакция.Посылка Get start)
                if ((this.fПосылка == null))
                {
                    this.fПосылка = new IIS.Postamat.DetailArrayOfПосылка(this);
                }
                IIS.Postamat.DetailArrayOfПосылка result = this.fПосылка;
                // *** Start programmer edit section *** (Транзакция.Посылка Get end)

                // *** End programmer edit section *** (Транзакция.Посылка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Транзакция.Посылка Set start)

                // *** End programmer edit section *** (Транзакция.Посылка Set start)
                this.fПосылка = value;
                // *** Start programmer edit section *** (Транзакция.Посылка Set end)

                // *** End programmer edit section *** (Транзакция.Посылка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТранзакцияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТранзакцияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТранзакцияE", typeof(IIS.Postamat.Транзакция));
                }
            }
            
            /// <summary>
            /// "ТранзакцияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТранзакцияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТранзакцияL", typeof(IIS.Postamat.Транзакция));
                }
            }
        }
    }
}
